image: adoptium/openjdk:17-jdk-hotspot

before_script:
  - apt-get update && apt-get install -y openjdk-17-jdk
  - export JAVA_HOME=/usr/lib/jvm/default-java
  - echo "Building project..."
  - mkdir -p lab/Compiler
  - cp -r ./src lab/Compiler/src
  - cp -r ./test lab/Compiler/test
  - cp -r ./lib lab/Compiler/lib
  - wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.1/junit-platform-console-standalone-1.8.1.jar
  - mv junit-platform-console-standalone-1.8.1.jar lab/Compiler/lib
  - chmod +x run-build.sh
  - ./run-build.sh


stages:
  - unit_test
  - lexer_test
  - parser_test
  - semantic_check_test


llvm_api_test:
  stage: unit_test
  script:
    - |
      ./run-test.sh \
      --select-class test.java.InstructionTest \
      --select-class test.java.ConstantTest \
      --select-class test.java.GlobalVariableTest \ 
      --select-class test.java.TypeTest

utils_test:
  stage: unit_test
  script:
    - |
      ./run-test.sh \
      --select-class test.java.StringUtilsTest 

lexer_public:
  stage: lexer_test
  dependencies:
    - utils_test
    - llvm_api_test
  script:
    - |
      ./run-test.sh \
      --select-class test.java.CompilerTest \
      --select-method testLexerPublic

lexer_error_private:
  stage: lexer_test
  dependencies:
    - utils_test
    - llvm_api_test
  script:
    - |
      ./run-test.sh \
      --select-class test.java.CompilerTest \
      --select-method testLexerErrorPrivate


parser_public:
  stage: parser_test
  dependencies:
    - lexer_public
    - lexer_error_private
  script:
    - |
      ./run-test.sh \
      --select-class test.java.CompilerTest \
      --select-method testParserPublic


parser_error_public:
  stage: parser_test
  dependencies:
    - lexer_public
    - lexer_error_private
  script:
    - |
      ./run-test.sh \
      --select-class test.java.CompilerTest \
      --select-method testParserErrorPublic


parser_error_private:
  stage: parser_test
  dependencies:
    - lexer_public
    - lexer_error_private
  script:
    - |
      ./run-test.sh \
      --select-class test.java.CompilerTest \
      --select-method testParserErrorPrivate

semantic_check_public:
  stage: semantic_check_test
  dependencies:
    - parser_public
    - parser_error_public
    - parser_error_private
  script:
    - |
      ./run-test.sh \
      --select-class test.java.CompilerTest \
      --select-method testSemanticCheckPublic

semantic_check_error_public:
  stage: semantic_check_test
  dependencies:
    - parser_public
    - parser_error_public
    - parser_error_private
  script:
    - |
      ./run-test.sh \
      --select-class test.java.CompilerTest \
      --select-method testSemanticCheckErrorPublic

semantic_check_error_private:
  stage: semantic_check_test
  dependencies:
    - parser_public
    - parser_error_public
    - parser_error_private
  script:
    - |
      ./run-test.sh \
      --select-class test.java.CompilerTest \
      --select-method testSemanticCheckErrorPrivate