image: adoptium/openjdk:17-jdk-hotspot

before_script:
  - apt-get update && apt-get install -y openjdk-17-jdk
  - export JAVA_HOME=/usr/lib/jvm/default-java

stages:
  - test

unit_tests:
  stage: test
  script:
    - java -version # 添加此行以检查 Java 版本
    - mkdir -p lab/Compiler
    - cp -r ./src lab/Compiler/src
    - cp -r ./test lab/Compiler/test
    - cp -r ./lib lab/Compiler/lib
    - wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-launcher/1.8.1/junit-platform-launcher-1.8.1.jar
    - mv junit-platform-launcher-1.8.1.jar lab/Compiler/lib
    - chmod +x run-test.sh
    - ./run-test.sh