image: adoptium/openjdk:17-jdk-hotspot-bullseye

stages:
  - test

unit_tests:
  stage: test
  script:
    - mkdir -p lab/Compiler/src/frontend/core lab/Compiler/src/utils lab/Compiler/test/java
    - cp -r ./src/frontend/core/* lab/Compiler/src/frontend/core/
    - cp -r ./src/utils/* lab/Compiler/src/utils/
    - cp ./test/java/CompilerTest.java lab/Compiler/test/java/
    - javac -encoding UTF-8 lab/Compiler/src/frontend/core/*.java
    - javac -encoding UTF-8 lab/Compiler/src/utils/*.java
    - javac -encoding UTF-8 lab/Compiler/test/java/CompilerTest.java
    - java -cp lab/Compiler/test/java:lab/Compiler/src/frontend/core:lab/Compiler/src/utils org.junit.runner.JUnitCore CompilerTest