# .github/workflows/java-build.yml

name: Java CI - Direct Compilation and Testing

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create output directories
        run: |
          mkdir -p bin
          mkdir -p test-output

      - name: Compile all source files
        run: |
          find src -name "*.java" -exec javac -d bin -cp bin {} +

      - name: Upload compiled classes as artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-classes
          path: bin/


  code-gen-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testcase: [
          "code-gen-private",
          "code-gen-public/A",
          "code-gen-public/B",
          "code-gen-public/C",
        ]
      fail-fast: false # 如果一个测试失败，是否停止其他测试

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download compiled classes from previous job
        uses: actions/download-artifact@v3
        with:
          name: compiled-classes
          path: bin/

      - name: Ensure script is executable
        run: chmod +x run-mips.sh

      - name: Run specific test
        run: |
          python3 test/python/code-gen-test-ci.py test/python/testcases/${{ matrix.testcase }} output.txt --script run-mips.sh

      - name: Display judge.log
        if: always() # 无论之前步骤的结果如何，此步骤总是会执行
        run: cat judge.log
